name: Run Django Tests
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # https://endoflife.date/python
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        # https://endoflife.date/django
        django-version: ["3.2", "4.2"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          cache: "pip"
          cache-dependency-path: "setup.cfg"
          python-version: ${{ matrix.python-version }}

      - run: pip install -U pip wheel
      - run: pip install django==${{ matrix.django-version }} -e .

      - name: Run tests
        run: python -m tests.example -v 2
